float *allocateV(int numItems);
float **allocateM(int numRows, int numCols);
int **allocateMint(int numRows, int numCols);
float ***allocateT(int numPlanes, int numRows, int numCols);
float **valueM(float value, int numRows, int numCols);
void freeV(float *V);
void freeM(float **M, int numRows);
void freeMint(int **M, int numRows);
void freeT(float ***T, int numPlanes, int numRows);
void copy_M_to(float **M1, float **M2, int numRows, int numCols);